author: LiveCodeBench Pro Team
author_email: shz060@ucsd.edu
difficulty: hard
instruction: "LiveCodeBench Pro (Mini) - external judge.\n\nThe agent must create\
  \ a C++17 solution file at /app/main.cpp.\nThis task does not include local test\
  \ cases. Instead, the test harness:\n  1) POSTs the code to the external judge (/submit)\
  \ to get a sid,\n  2) polls GET /result/{sid}?short=1 until status == \"done\",\n\
  \  3) passes only if the judge returns passed == true.\n\nEnvironment variables\
  \ (overridable at runtime):\n  - BASE_URL: judge base URL (default http://38.80.122.117:8081)\n\
  \  - PID: problem id (default 2096F)\n  - LANG: language (default cpp)\n  - CODE_PATH:\
  \ path to code (default /app/main.cpp)\n  - JUDGE_TIMEOUT_SECS: poll timeout seconds\
  \ (default 120)\n\nYou are a proud live streamer known as Gigi Murin. Today, you\
  \ will play a game with $n$ viewers numbered $1$ to $n$.\n\nIn the game, each player\
  \ is either a crewmate or an impostor. You don't know the role of each viewer.\n\
  \nThere are $m$ statements numbered $1$ to $m$, which are either true or false.\
  \ For each $i$ from $1$ to $m$, statement $i$ is one of two types:\n\n- $0\\:a_i\\\
  :b_i$ ($1 \\leq a_i \\leq b_i \\leq n$) -- there are no impostors among viewers\
  \ $a_i, a_i + 1, \\ldots, b_i$;\n- $1\\:a_i\\:b_i$ ($1 \\leq a_i \\leq b_i \\leq\
  \ n$) -- there is at least one impostor among viewers $a_i, a_i + 1, \\ldots, b_i$.\n\
  \nAnswer $q$ questions of the following form:\n\n- $l\\:r$ ($1 \\leq l \\leq r \\\
  leq m$) -- is it possible that statements $l, l + 1, \\ldots, r$ are all true?\n\
  \nNote that it is not guaranteed that there is at least one impostor among all viewers,\
  \ and it is not guaranteed that there is at least one crewmate among all viewers.\n\
  \n### Input\n\nEach test contains multiple test cases. The first line contains the\
  \ number of test cases $t$ ($1 \\le t \\le 10^4$). The description of the test cases\
  \ follows.\n\nThe first line of each test case contains two integers $n$, $m$ ($1\
  \ \\leq n, m \\leq 2 \\cdot 10^5$) -- the number of viewers, and the number of statements.\n\
  \nThe $i$-th of the next $m$ lines contains three integers $x_i$, $a_i$, $b_i$ ($x_i\
  \ \\in \\{0, 1\\}$, $1 \\leq a_i \\leq b_i \\leq n$) -- describing statement $i$.\n\
  \nThe next line contains a single integer $q$ ($1 \\le q \\le 2 \\cdot 10^5$) --\
  \ the number of questions.\n\nEach of the next $q$ lines contains two integers $l$\
  \ and $r$ ($1 \\leq l \\leq r \\leq m$) -- describing a question.\n\nIt is guaranteed\
  \ that the sum of $n$ over all test cases does not exceed $2 \\cdot 10^5$, the sum\
  \ of $m$ over all test cases does not exceed $2 \\cdot 10^5$, and the sum of $q$\
  \ over all test cases does not exceed $2 \\cdot 10^5$.\n\n### Output\n\nFor each\
  \ question, output \"YES\" if it is possible that the requested statements are all\
  \ true. Otherwise, output \"NO\".\n\nYou can output the answer in any case (upper\
  \ or lower). For example, the strings \"yEs\", \"yes\", \"Yes\", and \"YES\" will\
  \ be recognized as positive responses.\n\n### Example\n\n#### Input #1\n\n```\n\n\
  4\n\n4 3\n\n1 1 3\n\n1 2 4\n\n0 2 3\n\n1\n\n1 3\n\n5 2\n\n0 1 5\n\n1 1 5\n\n3\n\n\
  1 1\n\n2 2\n\n1 2\n\n1 2\n\n0 1 1\n\n1 1 1\n\n2\n\n1 1\n\n2 2\n\n7 9\n\n1 2 2\n\n\
  1 4 5\n\n0 5 6\n\n1 2 2\n\n1 1 1\n\n0 4 7\n\n0 3 7\n\n0 2 7\n\n0 6 6\n\n5\n\n1 5\n\
  \n2 6\n\n3 7\n\n4 8\n\n5 9\n\n```\n\n#### Output #1\n\n```\nYES\nYES\nYES\nNO\n\
  YES\nYES\nYES\nNO\nYES\nNO\nYES\n```\n\n### Note\n\nIn the first test case, there\
  \ are $4$ viewers and $3$ statements. The statements are as follows:\n\n- Statement\
  \ $1$: There is at least one impostor among viewers $1$, $2$, and $3$;\n- Statement\
  \ $2$: There is at least one impostor among viewers $2$, $3$, and $4$;\n- Statement\
  \ $3$: There are no impostors among viewers $2$ and $3$.\n\nWe can see that it is\
  \ possible that statements $1$, $2$, and $3$ are all true. For example, this is\
  \ one possible scenario:\n\n- Viewer $1$ is an impostor;\n- Viewer $2$ is a crewmate;\n\
  - Viewer $3$ is a crewmate;\n- Viewer $4$ is an impostor.\n\nIn the second test\
  \ case, there are $5$ viewers and $2$ statements. The statements are as follows:\n\
  \n- Statement $1$: There is at least one impostor among viewers $1$, $2$, $3$, $4$,\
  \ and $5$;\n- Statement $2$: There are no impostors among viewers $1$, $2$, $3$,\
  \ $4$, and $5$.\n\nWe can see that it is possible that statement $1$ is true, and\
  \ it is possible that statement $2$ is true. However, it is not possible that both\
  \ statements $1$ and $2$ are true."
max_agent_timeout_sec: 300
max_test_timeout_sec: 180
tags: []
