author: LiveCodeBench Pro Team
author_email: shz060@ucsd.edu
difficulty: medium
instruction: "LiveCodeBench Pro (Mini) - external judge.\n\nThe agent must create\
  \ a C++17 solution file at /app/main.cpp.\nThis task does not include local test\
  \ cases. Instead, the test harness:\n  1) POSTs the code to the external judge (/submit)\
  \ to get a sid,\n  2) polls GET /result/{sid}?short=1 until status == \"done\",\n\
  \  3) passes only if the judge returns passed == true.\n\nEnvironment variables\
  \ (overridable at runtime):\n  - BASE_URL: judge base URL (default http://38.80.122.117:8081)\n\
  \  - PID: problem id (default 2000H)\n  - LANG: language (default cpp)\n  - CODE_PATH:\
  \ path to code (default /app/main.cpp)\n  - JUDGE_TIMEOUT_SECS: poll timeout seconds\
  \ (default 120)\n\nKsyusha decided to start a game development company. To stand\
  \ out among competitors and achieve success, she decided to write her own game engine.\
  \ The engine must support a set initially consisting of $n$ distinct integers $a_1,\
  \ a_2, \\ldots, a_n$.\n\nThe set will undergo $m$ operations sequentially. The operations\
  \ can be of the following types:\n\n- Insert element $x$ into the set;\n- Remove\
  \ element $x$ from the set;\n- Report the $k$-load of the set.\n\nThe $k$-load of\
  \ the set is defined as the minimumpositive integer $d$ such that the integers $d,\
  \ d + 1, \\ldots, d + (k - 1)$ do not appear in this set. For example, the $3$-load\
  \ of the set $\\{3, 4, 6, 11\\}$ is $7$, since the integers $7, 8, 9$ are absent\
  \ from the set, and no smaller value fits.\n\nKsyusha is busy with management tasks,\
  \ so you will have to write the engine. Implement efficient support for the described\
  \ operations.\n\n### Input\n\nThe first line contains an integer $t$ ($1 \\le t\
  \ \\le 10^4$) -- the number of test cases.\n\nThe following lines describe the test\
  \ cases.\n\nThe first line contains an integer $n$ ($1 \\le n \\le 2 \\cdot 10^5$) --\
  \ the initial size of the set.\n\nThe second line contains $n$ integers $a_1, a_2,\
  \ \\ldots, a_n$ ($1 \\le a_1 < a_2 < \\ldots < a_n \\le 2 \\cdot 10^6$) -- the initial\
  \ state of the set.\n\nThe third line contains an integer $m$ ($1 \\le m \\le 2\
  \ \\cdot 10^5$) -- the number of operations.\n\nThe next $m$ lines contain the operations.\
  \ The operations are given in the following format:\n\n- + $x$ ($1 \\le x \\le 2\
  \ \\cdot 10^6$) -- insert element $x$ into the set (it is guaranteed that $x$ is\
  \ not in the set);\n- - $x$ ($1 \\le x \\le 2 \\cdot 10^6$) -- remove element $x$\
  \ from the set (it is guaranteed that $x$ is in the set);\n- ? $k$ ($1 \\le k \\\
  le 2 \\cdot 10^6$) -- output the value of the $k$-load of the set.\n\nIt is guaranteed\
  \ that the sum of $n$ across all test cases does not exceed $2 \\cdot 10^5$, and\
  \ the same holds for $m$.\n\n### Output\n\nFor each test case, output the answers\
  \ to the operations of type \"?\".\n\n### Example\n\n#### Input #1\n\n```\n\n3\n\
  \n5\n\n1 2 5 905 2000000\n\n15\n\n\\- 2\n\n? 2\n\n? 1\n\n\\- 1\n\n? 1\n\n\\+ 4\n\
  \n\\+ 2\n\n? 2\n\n\\+ 6\n\n\\- 4\n\n\\+ 7\n\n? 2\n\n? 3\n\n? 4\n\n? 2000000\n\n\
  5\n\n3 4 5 6 8\n\n9\n\n? 5\n\n\\- 5\n\n? 5\n\n\\+ 1\n\n? 2\n\n\\- 6\n\n\\- 8\n\n\
  \\+ 6\n\n? 5\n\n5\n\n6 7 8 9 10\n\n10\n\n? 5\n\n\\- 6\n\n? 4\n\n\\- 10\n\n\\+ 5\n\
  \n\\- 8\n\n\\+ 3\n\n\\+ 2\n\n\\- 3\n\n\\+ 10\n\n```\n\n#### Output #1\n\n```\n2\
  \ 2 1 6 3 8 8 2000001\n9 9 9 7\n1 1\n```"
max_agent_timeout_sec: 300
max_test_timeout_sec: 180
tags: []
