author: LiveCodeBench Pro Team
author_email: shz060@ucsd.edu
difficulty: hard
instruction: "LiveCodeBench Pro (Mini) - external judge.\n\nThe agent must create\
  \ a C++17 solution file at /app/main.cpp.\nThis task does not include local test\
  \ cases. Instead, the test harness:\n  1) POSTs the code to the external judge (/submit)\
  \ to get a sid,\n  2) polls GET /result/{sid}?short=1 until status == \"done\",\n\
  \  3) passes only if the judge returns passed == true.\n\nEnvironment variables\
  \ (overridable at runtime):\n  - BASE_URL: judge base URL (default http://38.80.122.117:8081)\n\
  \  - PID: problem id (default 2023E)\n  - LANG: language (default cpp)\n  - CODE_PATH:\
  \ path to code (default /app/main.cpp)\n  - JUDGE_TIMEOUT_SECS: poll timeout seconds\
  \ (default 120)\n\nIn the heart of an ancient kingdom grows the legendary Tree of\
  \ Life -- the only one of its kind and the source of magical power for the entire\
  \ world. The tree consists of $n$ nodes. Each node of this tree is a magical source,\
  \ connected to other such sources through magical channels (edges). In total, there\
  \ are $n-1$ channels in the tree, with the $i$-th channel connecting nodes $v_i$\
  \ and $u_i$. Moreover, there exists a unique simple path through the channels between\
  \ any two nodes in the tree.\n\nHowever, the magical energy flowing through these\
  \ channels must be balanced; otherwise, the power of the Tree of Life may disrupt\
  \ the natural order and cause catastrophic consequences. The sages of the kingdom\
  \ discovered that when two magical channels converge at a single node, a dangerous\
  \ \"magical resonance vibration\" occurs between them. To protect the Tree of Life\
  \ and maintain its balance, it is necessary to select several paths and perform\
  \ special rituals along them. A path is a sequence of distinct nodes $v_1, v_2,\
  \ \\ldots, v_k$, where each pair of adjacent nodes $v_i$ and $v_{i+1}$ is connected\
  \ by a channel. When the sages perform a ritual along such a path, the resonance\
  \ vibration between the channels $(v_i, v_{i+1})$ and $(v_{i+1}, v_{i+2})$ is blocked\
  \ for each $1 \\leq i \\leq k - 2$.\n\nThe sages' task is to select the minimum\
  \ number of paths and perform rituals along them to block all resonance vibrations.\
  \ This means that for every pair of channels emanating from a single node, there\
  \ must exist at least one selected path that contains both of these channels.\n\n\
  Help the sages find the minimum number of such paths so that the magical balance\
  \ of the Tree of Life is preserved, and its power continues to nourish the entire\
  \ world!\n\n### Input\n\nEach test consists of multiple test cases. The first line\
  \ contains a single integer $t$ ($1 \\leq t \\leq 4 \\cdot 10^4$) -- the number\
  \ of test cases. The description of the test cases follows.\n\nThe first line of\
  \ each test case contains a single integer $n$ ($2 \\leq n \\leq 5 \\cdot 10^5$)\
  \ -- the number of nodes in the Tree of Life.\n\nThe $i$-th of the following $n\
  \ - 1$ lines of each test case contains two integers $v_i$ and $u_i$ ($1 \\leq v_i\
  \ < u_i \\leq n$) -- the channel connecting nodes $v_i$ and $u_i$.\n\nIt is guaranteed\
  \ that there exists a unique simple path through the channels between any two nodes.\n\
  \nIt is guaranteed that the sum of $n$ over all test cases does not exceed $5 \\\
  cdot 10^5$.\n\n### Output\n\nFor each test case, output a single integer -- the\
  \ minimum number of paths that the sages need to select to prevent a catastrophe.\n\
  \n### Example\n\n#### Input #1\n\n```\n\n5\n\n4\n\n1 2\n\n2 3\n\n3 4\n\n2\n\n1 2\n\
  \n4\n\n1 2\n\n1 3\n\n1 4\n\n8\n\n3 7\n\n2 4\n\n1 2\n\n2 5\n\n3 6\n\n1 3\n\n3 8\n\
  \n6\n\n2 3\n\n1 2\n\n3 6\n\n1 5\n\n1 4\n\n```\n\n#### Output #1\n\n```\n1\n0\n3\n\
  7\n3\n```\n\n### Note\n\nIn the first test case, there are two pairs of channels\
  \ emanating from a single node: $(1, 2)$ and $(2, 3)$, $(2, 3)$ and $(3, 4)$. It\
  \ is sufficient to perform the ritual along the path $1-2-3-4$. Thus, the answer\
  \ is $1$.\n\nIn the second test case, there are no pairs of channels emanating from\
  \ a single node, so the answer is $0$.\n\nIn the third test case, rituals can be\
  \ performed along the paths $2-1-3$, $2-1-4$, and $3-1-4$."
max_agent_timeout_sec: 300
max_test_timeout_sec: 180
tags: []
