author: LiveCodeBench Pro Team
author_email: shz060@ucsd.edu
difficulty: medium
instruction: "LiveCodeBench Pro (Mini) - external judge.\n\nThe agent must create\
  \ a C++17 solution file at /app/main.cpp.\nThis task does not include local test\
  \ cases. Instead, the test harness:\n  1) POSTs the code to the external judge (/submit)\
  \ to get a sid,\n  2) polls GET /result/{sid}?short=1 until status == \"done\",\n\
  \  3) passes only if the judge returns passed == true.\n\nEnvironment variables\
  \ (overridable at runtime):\n  - BASE_URL: judge base URL (default http://38.80.122.117:8081)\n\
  \  - PID: problem id (default 1990F)\n  - LANG: language (default cpp)\n  - CODE_PATH:\
  \ path to code (default /app/main.cpp)\n  - JUDGE_TIMEOUT_SECS: poll timeout seconds\
  \ (default 120)\n\nYou are given an array $a$ of size $n$.\n\nA segment $[l, r](1\
  \ \\le l < r \\le n)$ is called a polygonal segment only if the following conditions\
  \ hold:\n\n- $(r-l+1) \\geq 3$;\n- Considering $a_l, a_{l+1}, \\ldots, a_r$ as side\
  \ lengths, these sides can form a polygon with $(r-l+1)$ sides.\n\nProcess $q$ queries\
  \ of two types:\n\n- \"1 l r\": find the length of the longest segment among all\
  \ polygonal segments $[l_0,r_0]$ satisfying $l \\le l_0 \\le r_0 \\le r$. If there\
  \ is no such polygonal segment, output $-1$ instead;\n- \"2 i x\": assign $a_i :=\
  \ x$.\n\n### Input\n\nThe first line contains an integer $t$ ($1 \\leq t \\leq 10^4$) --\
  \ the number of test cases.\n\nFor each test case:\n\n- The first line of each testcase\
  \ contains two integers $n$, $q$ ($4 \\le n \\le 2\\cdot 10^5$, $1 \\le q \\le 10^5$);\n\
  - The second line of each testcase contains $n$ integers $a_1,a_2,\\ldots, a_n$\
  \ ($1 \\le a_i \\le 10^{12}$);\n- The following $q$ lines contain the description\
  \ of queries. Each line is of one of two types:\n- \"1 l r\" ($1 \\le l < r \\le\
  \ n$, $r-l+1\\ge 3$);\n- \"2 i x\" ($1 \\le i \\le n$, $1 \\le x \\le 10^{12}$).\n\
  \nIt is guaranteed that the sum of $n$ over all test cases will not exceed $2 \\\
  cdot 10^5$, and the sum of $q$ over all test cases will not exceed $10^5$.\n\n###\
  \ Output\n\nFor each query, if there is no suitable segment, output $-1$ in a new\
  \ line. Otherwise, output the length of the longest segment satisfying the condition\
  \ above in a new line.\n\n### Example\n\n#### Input #1\n\n```\n\n2\n\n5 6\n\n3 1\
  \ 2 2 8\n\n1 1 3\n\n1 1 4\n\n1 1 5\n\n2 1 5\n\n1 1 4\n\n1 1 5\n\n4 10\n\n500000000000\
  \ 500000000000 1000000000000 500000000000\n\n1 1 3\n\n1 2 4\n\n1 1 4\n\n2 1 499999999999\n\
  \n2 3 999999999999\n\n1 1 3\n\n1 2 4\n\n1 1 4\n\n2 3 1000000000000\n\n1 1 3\n\n\
  ```\n\n#### Output #1\n\n```\n-1\n4\n4\n3\n5\n-1\n-1\n4\n-1\n3\n4\n-1\n```\n\n###\
  \ Note\n\nIn the first query of the first test case, there is no polygonal segment\
  \ under the given condition. For example, considering segment $[1,3]$, you can not\
  \ form a triangle with side lengths of $a_1=3$, $a_2=1$, and $a_3=2$.\n\nIn the\
  \ second query of the first test case, the longest polygonal segment is $[1,4]$.\
  \ You can form a quadrilateral with side lengths of $a_1=3$, $a_2=1$, $a_3=2$, and\
  \ $a_4=2$.\n\n![](https://espresso.codeforces.com/c8da964ded1680db263ba74efbf576b1cc520708.png)An\
  \ example of a quadrilateral with side lengths of $3$, $1$, $2$, and $2$."
max_agent_timeout_sec: 300
max_test_timeout_sec: 180
tags: []
