author: LiveCodeBench Pro Team
author_email: shz060@ucsd.edu
difficulty: easy
instruction: "LiveCodeBench Pro (Mini) - external judge.\n\nThe agent must create\
  \ a C++17 solution file at /app/main.cpp.\nThis task does not include local test\
  \ cases. Instead, the test harness:\n  1) POSTs the code to the external judge (/submit)\
  \ to get a sid,\n  2) polls GET /result/{sid}?short=1 until status == \"done\",\n\
  \  3) passes only if the judge returns passed == true.\n\nEnvironment variables\
  \ (overridable at runtime):\n  - BASE_URL: judge base URL (default http://38.80.122.117:8081)\n\
  \  - PID: problem id (default 2036A)\n  - LANG: language (default cpp)\n  - CODE_PATH:\
  \ path to code (default /app/main.cpp)\n  - JUDGE_TIMEOUT_SECS: poll timeout seconds\
  \ (default 120)\n\nBoris Notkin composes melodies. He represents them as a sequence\
  \ of notes, where each note is encoded as an integer from $0$ to $127$ inclusive.\
  \ The interval between two notes $a$ and $b$ is equal to $|a - b|$ semitones.\n\n\
  Boris considers a melody perfect if the interval between each two adjacent notes\
  \ is either $5$ semitones or $7$ semitones.\n\nAfter composing his latest melodies,\
  \ he enthusiastically shows you his collection of works. Help Boris Notkin understand\
  \ whether his melodies are perfect.\n\n### Input\n\nThe first line contains an integer\
  \ $t$ ($1 \\leq t \\leq 1000$) -- the number of melodies.\n\nEach melody is described\
  \ by two lines.\n\nThe first line contains an integer $n$ ($2 \\leq n \\leq 50$)\
  \ -- the number of notes in the melody.\n\nThe second line contains $n$ integers\
  \ $a_{1}, a_{2}, \\dots, a_{n}$ ($0 \\leq a_{i} \\leq 127$) -- the notes of the\
  \ melody.\n\n### Output\n\nFor each melody, output \"YES\", if it is perfect; otherwise,\
  \ output \"NO\".\n\nYou can output the answer in any case (upper or lower). For\
  \ example, the strings \"yEs\", \"yes\", \"Yes\", and \"YES\" will be recognized\
  \ as positive responses.\n\n### Example\n\n#### Input #1\n\n```\n\n8\n\n2\n\n114\
  \ 109\n\n2\n\n17 10\n\n3\n\n76 83 88\n\n8\n\n38 45 38 80 85 92 99 106\n\n5\n\n63\
  \ 58 65 58 65\n\n8\n\n117 124 48 53 48 43 54 49\n\n5\n\n95 102 107 114 121\n\n10\n\
  \n72 77 82 75 70 75 68 75 68 75\n\n```\n\n#### Output #1\n\n```\nYES\nYES\nYES\n\
  NO\nYES\nNO\nYES\nYES\n```"
max_agent_timeout_sec: 300
max_test_timeout_sec: 180
tags: []
