author: LiveCodeBench Pro Team
author_email: shz060@ucsd.edu
difficulty: medium
instruction: "LiveCodeBench Pro (Mini) - external judge.\n\nThe agent must create\
  \ a C++17 solution file at /app/main.cpp.\nThis task does not include local test\
  \ cases. Instead, the test harness:\n  1) POSTs the code to the external judge (/submit)\
  \ to get a sid,\n  2) polls GET /result/{sid}?short=1 until status == \"done\",\n\
  \  3) passes only if the judge returns passed == true.\n\nEnvironment variables\
  \ (overridable at runtime):\n  - BASE_URL: judge base URL (default http://38.80.122.117:8081)\n\
  \  - PID: problem id (default 1988D)\n  - LANG: language (default cpp)\n  - CODE_PATH:\
  \ path to code (default /app/main.cpp)\n  - JUDGE_TIMEOUT_SECS: poll timeout seconds\
  \ (default 120)\n\nYou, the monster killer, want to kill a group of monsters. The\
  \ monsters are on a tree with $n$ vertices. On vertex with number $i$ ($1\\le i\\\
  le n$), there is a monster with $a_i$ attack points. You want to battle with monsters\
  \ for $10^{100}$ rounds.\n\nIn each round, the following happens in order:\n\n1.\
  \ All living monsters attack you. Your health decreases by the sum of attack points\
  \ of all living monsters.\n2. You select some (possibly all or none) monsters and\
  \ kill them. After being killed, the monster will not be able to do any attacks\
  \ in the future.\n\nThere is a restriction: in one round, you cannot kill two monsters\
  \ that are directly connected by an edge.\n\nIf you choose what monsters to attack\
  \ optimally, what is the smallest health decrement you can have after all rounds?\n\
  \n### Input\n\nEach test contains multiple test cases. The first line contains the\
  \ number of test cases $t$ ($1 \\le t \\le 10^4$). Description of the test cases\
  \ follows.\n\nThe first line of each test case contains an integer $n$ ($1\\le n\\\
  le 3\\cdot 10^5$).\n\nThe second line of each test case contains $n$ integers $a_1,\\\
  ldots,a_n$ ($1\\le a_i\\le 10^{12}$).\n\nThe following $n-1$ lines each contain\
  \ two integers $x,y$ ($1\\le x,y\\le n$), denoting an edge on the tree connecting\
  \ vertex $x$ and $y$.\n\nIt is guaranteed that the sum of $n$ over all test cases\
  \ does not exceed $3\\cdot 10^5$.\n\n### Output\n\nFor each test case, print one\
  \ integer: the minimum possible health decrement.\n\n### Example\n\n#### Input #1\n\
  \n```\n\n3\n\n1\n\n1000000000000\n\n5\n\n47 15 32 29 23\n\n1 2\n\n1 3\n\n2 4\n\n\
  2 5\n\n7\n\n8 10 2 3 5 7 4\n\n1 2\n\n1 4\n\n3 2\n\n5 3\n\n6 2\n\n7 5\n\n```\n\n\
  #### Output #1\n\n```\n1000000000000\n193\n57\n```\n\n### Note\n\nIn the first test\
  \ case, an optimal sequence of operations would be:\n\n- In the first round: first,\
  \ receive the attack from the monster on vertex $1$, so your health decreases by\
  \ $10^{12}$. Then kill the monster on vertex $1$.\n- In the second round to the\
  \ $10^{100}$-th round: all monsters have been killed, so nothing happens.\n\nThe\
  \ total health decrement is $10^{12}$.\n\nIn the second test case, an optimal sequence\
  \ of operations would be:\n\n- In the first round: first, receive the attack from\
  \ the monster on vertex $1,2,3,4,5$, so your health decreases by $47+15+32+29+23=146$.\
  \ Then kill the monsters on vertex $1,4,5$.\n- In the second round: first, receive\
  \ the attack from the monster on vertex $2,3$, so your health decreases by $15+32=47$.\
  \ Then kill the monsters on vertex $2,3$.\n- In the third round to the $10^{100}$-th\
  \ round: all monsters have been killed, so nothing happens.\n\nThe total health\
  \ decrement is $193$.\n\nIn the third test case, an optimal sequence of operations\
  \ would be:\n\n- In the first round: first, receive the attack from the monster\
  \ on vertex $1,2,3,4,5,6,7$, so your health decreases by $8+10+2+3+5+7+4=39$. Then\
  \ kill the monsters on vertex $1,3,6,7$.\n- In the second round: first, receive\
  \ the attack from the monster on vertex $2,4,5$, so your health decreases by $10+3+5=18$.\
  \ Then kill the monsters on vertex $2,4,5$.\n- In the third round to the $10^{100}$-th\
  \ round: all monsters have been killed, so nothing happens.\n\nThe total health\
  \ decrement is $57$."
max_agent_timeout_sec: 300
max_test_timeout_sec: 180
tags: []
