author: LiveCodeBench Pro Team
author_email: shz060@ucsd.edu
difficulty: hard
instruction: "LiveCodeBench Pro (Mini) - external judge.\n\nThe agent must create\
  \ a C++17 solution file at /app/main.cpp.\nThis task does not include local test\
  \ cases. Instead, the test harness:\n  1) POSTs the code to the external judge (/submit)\
  \ to get a sid,\n  2) polls GET /result/{sid}?short=1 until status == \"done\",\n\
  \  3) passes only if the judge returns passed == true.\n\nEnvironment variables\
  \ (overridable at runtime):\n  - BASE_URL: judge base URL (default http://38.80.122.117:8081)\n\
  \  - PID: problem id (default 2101F)\n  - LANG: language (default cpp)\n  - CODE_PATH:\
  \ path to code (default /app/main.cpp)\n  - JUDGE_TIMEOUT_SECS: poll timeout seconds\
  \ (default 120)\n\nYou are given a tree with $n$ vertices, where each vertex can\
  \ be colored red, blue, or white. The coolness of a coloring is defined as the maximum\
  \ distance$^{\\text{∗}}$ between a red and a blue vertex.\n\nFormally, if we denote\
  \ the color of the $i$-th vertex as $c_i$, the coolness of a coloring is $\\max\
  \ d(u, v)$ over all pairs of vertices $1\\le u, v\\le n$ where $c_u$ is red and\
  \ $c_v$ is blue. If there are no red or no blue vertices, the coolness is zero.\n\
  \nYour task is to calculate the sum of coolness over all $3^n$ possible colorings\
  \ of the tree, modulo $998\\,244\\,353$.\n\n$^{\\text{∗}}$The distance between two\
  \ vertices $a$ and $b$ in a tree is equal to the number of edges on the unique simple\
  \ path between vertex $a$ and vertex $b$.\n\n### Input\n\nEach test contains multiple\
  \ test cases. The first line contains the number of test cases $t$ ($1 \\le t \\\
  le 50$). The description of the test cases follows.\n\nThe first line of each test\
  \ case contains a single integer $n$ ($2\\le n\\le 3000$) -- the number of vertices\
  \ in the tree.\n\nEach of the next $n - 1$ lines contains two integers $u$ and $v$\
  \ ($1\\le u, v\\le n$) -- the endpoints of the edges of the tree.\n\nIt is guaranteed\
  \ that the given edges form a tree.\n\nIt is guaranteed that the sum of $n$ over\
  \ all test cases does not exceed $3000$.\n\n### Output\n\nFor each test case, output\
  \ the sum of coolness over all $3^n$ possible colorings of the tree, modulo $998\\\
  ,244\\,353$.\n\n### Example\n\n#### Input #1\n\n```\n\n3\n\n3\n\n1 2\n\n2 3\n\n\
  6\n\n1 2\n\n1 3\n\n1 4\n\n3 5\n\n5 6\n\n17\n\n1 2\n\n1 3\n\n1 4\n\n1 5\n\n2 6\n\n\
  2 7\n\n2 8\n\n3 9\n\n3 10\n\n7 11\n\n7 12\n\n11 13\n\n13 14\n\n14 15\n\n10 16\n\n\
  16 17\n\n```\n\n#### Output #1\n\n```\n18\n1920\n78555509\n```\n\n### Note\n\nIn\
  \ the first test case, there are $12$ colorings that have at least one blue and\
  \ one red node. The following pictures show their coloring and their coolness:\n\
  \n![](https://espresso.codeforces.com/15dd2aaf8c69f02fa71a455d40f5b7dc08ca4311.png)All\
  \ these colorings have coolness $2$![](https://espresso.codeforces.com/921c5954be27aa779f596f91411b63f11d4f661a.png)All\
  \ these colorings have coolness $1$\n\nTherefore, the sum of coolness over all possible\
  \ colorings is $6\\cdot 2 + 6\\cdot 1 = 18$.\n\nIn the second test case, the following\
  \ are some examples of colorings with a coolness of $3$:\n\n![](https://espresso.codeforces.com/24a643356f55c5c5cb134dfece58f952a4c90566.png)"
max_agent_timeout_sec: 300
max_test_timeout_sec: 180
tags: []
