author: LiveCodeBench Pro Team
author_email: shz060@ucsd.edu
difficulty: easy
instruction: "LiveCodeBench Pro (Mini) - external judge.\n\nThe agent must create\
  \ a C++17 solution file at /app/main.cpp.\nThis task does not include local test\
  \ cases. Instead, the test harness:\n  1) POSTs the code to the external judge (/submit)\
  \ to get a sid,\n  2) polls GET /result/{sid}?short=1 until status == \"done\",\n\
  \  3) passes only if the judge returns passed == true.\n\nEnvironment variables\
  \ (overridable at runtime):\n  - BASE_URL: judge base URL (default http://38.80.122.117:8081)\n\
  \  - PID: problem id (default 2043A)\n  - LANG: language (default cpp)\n  - CODE_PATH:\
  \ path to code (default /app/main.cpp)\n  - JUDGE_TIMEOUT_SECS: poll timeout seconds\
  \ (default 120)\n\nInitially, you have a coin with value $n$. You can perform the\
  \ following operation any number of times (possibly zero):\n\n- transform one coin\
  \ with value $x$, where $x$ is greater than $3$ ($x>3$), into two coins with value\
  \ $\\lfloor \\frac{x}{4} \\rfloor$.\n\nWhat is the maximum number of coins you can\
  \ have after performing this operation any number of times?\n\n### Input\n\nThe\
  \ first line contains one integer $t$ ($1 \\le t \\le 10^4$) -- the number of test\
  \ cases.\n\nEach test case consists of one line containing one integer $n$ ($1 \\\
  le n \\le 10^{18}$).\n\n### Output\n\nFor each test case, print one integer -- the\
  \ maximum number of coins you can have after performing the operation any number\
  \ of times.\n\n### Example\n\n#### Input #1\n\n```\n\n4\n\n1\n\n5\n\n16\n\n1000000000000000000\n\
  \n```\n\n#### Output #1\n\n```\n1\n2\n4\n536870912\n```\n\n### Note\n\nIn the first\
  \ example, you have a coin of value $1$, and you can't do anything with it. So,\
  \ the answer is $1$.\n\nIn the second example, you can transform a coin of value\
  \ $5$ into two coins with value $1$.\n\nIn the third example, you can transform\
  \ a coin of value $16$ into two coins with value $4$. Each of the resulting coins\
  \ can be transformed into two coins with value $1$."
max_agent_timeout_sec: 300
max_test_timeout_sec: 180
tags: []
